name: Frontend Pull-Request Sanity Checks
on:
    pull_request:
        types: [opened, reopened, edited]
env:
    NODE_VERSION: 20
jobs:
    prepare_workflow:
        name: Prepare Workflow
        runs-on: ubuntu-latest
        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with: 
                node-version: ${{env.NODE_VERSION}}
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Move To 'meshapp' Directory
              run: |
                cd meshapp  
            - name: Install Node Modules
              run: |
                npm install
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: prepare_workflow
        steps:
            - name: Run NPM 'build' Script
              run: |
                npm run build
    test:
        name: Test
        runs-on: ubuntu-latest
        needs: [prepare_workflow, build]
        steps:
            - name: Run NPM 'test' Script
              run: |
                npm run test
