name: Frontend Pull-Request Sanity Checks
on:
    pull_request:
        types: [opened, reopened, synchronize]
env:
    NODE_VERSION: 20
jobs:
    build_lint_and_test_frontend:
        name: Build, Lint, and Test Frontend
        runs-on: ubuntu-latest
        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with: 
                node-version: ${{env.NODE_VERSION}}
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Node Modules
              working-directory: ./meshapp
              run: |
                npm install
            - name: Run NPM 'build' Script (implicitly runs eslint)
              working-directory: ./meshapp
              run: |
                npm run build
            - name: Run NPM 'test' Script
              working-directory: ./meshapp
              run: |
                npm run test
